; Generated by ELang compiler v0.2.0
extern print
extern print_str
extern print_int
extern print_hex
extern read_input
extern exit
extern str_len
extern str_dup
extern str_cmp
extern str_cat
extern sys_open
extern sys_close
extern sys_read
extern sys_write
extern sys_getpid
extern sys_exit
extern sys_brk
extern panic_handler
extern assert_handler
section .data
  str_0: db 'A', 'r', 'r', 'a', 'y', ' ', 't', 'e', 's', 't', 0x0A, 0
  str_1: db 'f', 'i', 'r', 's', 't', ':', ' ', 0
  str_2: db 0x0A, 0
  str_3: db 't', 'h', 'i', 'r', 'd', ':', ' ', 0
  str_4: db 0x0A, 0
  str_5: db 'l', 'a', 's', 't', ':', ' ', 0
  str_6: db 0x0A, 0
  str_7: db 'l', 'e', 'n', 'g', 't', 'h', ':', ' ', 0
  str_8: db 0x0A, 0
  str_9: db 's', 'u', 'm', ':', ' ', 0
  str_10: db 0x0A, 0
  str_11: db 'a', 'r', 'r', '2', '[', '1', ']', ':', ' ', 0
  str_12: db 0x0A, 0
section .text
global _start


global _main
_main:
    push rbp
    mov rbp, rsp
    push rbx
    push r12
    push r13
    push r14
    push r15
    sub rsp, 256
    sub rsp, 48
    mov qword [rsp], 5
    mov rax, 10
    mov [rsp+8], rax
    mov rax, 20
    mov [rsp+16], rax
    mov rax, 30
    mov [rsp+24], rax
    mov rax, 40
    mov [rsp+32], rax
    mov rax, 50
    mov [rsp+40], rax
    lea rax, [rsp+8]
    mov [rbp-48], rax
    mov rax, [rbp-48]
    push rax
    mov rax, 0
    mov rcx, rax
    pop rax
    mov rax, [rax+rcx*8]
    mov [rbp-56], rax
    mov rax, [rbp-48]
    push rax
    mov rax, 2
    mov rcx, rax
    pop rax
    mov rax, [rax+rcx*8]
    mov [rbp-64], rax
    mov rax, [rbp-48]
    push rax
    mov rax, 4
    mov rcx, rax
    pop rax
    mov rax, [rax+rcx*8]
    mov [rbp-72], rax
    mov rax, [rbp-48]
    mov rax, [rax-8]
    mov [rbp-80], rax
    lea rax, [str_0]
    mov rdi, rax
    call print_str
    lea rax, [str_1]
    mov rdi, rax
    call print_str
    mov rax, [rbp-56]
    mov rdi, rax
    call print_int
    lea rax, [str_2]
    mov rdi, rax
    call print_str
    lea rax, [str_3]
    mov rdi, rax
    call print_str
    mov rax, [rbp-64]
    mov rdi, rax
    call print_int
    lea rax, [str_2]
    mov rdi, rax
    call print_str
    lea rax, [str_5]
    mov rdi, rax
    call print_str
    mov rax, [rbp-72]
    mov rdi, rax
    call print_int
    lea rax, [str_2]
    mov rdi, rax
    call print_str
    lea rax, [str_7]
    mov rdi, rax
    call print_str
    mov rax, [rbp-80]
    mov rdi, rax
    call print_int
    lea rax, [str_2]
    mov rdi, rax
    call print_str
    mov rax, 0
    mov [rbp-88], rax
    mov rax, 0
    mov [rbp-96], rax
L13:
    mov rax, [rbp-96]
    push rax
    mov rax, [rbp-48]
    mov rax, [rax-8]
    mov rbx, rax
    pop rax
    cmp rax, rbx
    setl al
    movzx rax, al
    cmp rax, 0
    je L14
    mov rax, [rbp-88]
    push rax
    mov rax, [rbp-48]
    push rax
    mov rax, [rbp-96]
    mov rcx, rax
    pop rax
    mov rax, [rax+rcx*8]
    mov rbx, rax
    pop rax
    add rax, rbx
    mov [rbp-88], rax
    mov rax, [rbp-96]
    push rax
    mov rax, 1
    mov rbx, rax
    pop rax
    add rax, rbx
    mov [rbp-96], rax
    jmp L13
L14:
    lea rax, [str_9]
    mov rdi, rax
    call print_str
    mov rax, [rbp-88]
    mov rdi, rax
    call print_int
    lea rax, [str_2]
    mov rdi, rax
    call print_str
    mov rax, 5
    mov [rbp-104], rax
    sub rsp, 32
    mov qword [rsp], 3
    mov rax, [rbp-104]
    mov [rsp+8], rax
    mov rax, [rbp-104]
    push rax
    mov rax, 1
    mov rbx, rax
    pop rax
    add rax, rbx
    mov [rsp+16], rax
    mov rax, [rbp-104]
    push rax
    mov rax, 2
    mov rbx, rax
    pop rax
    imul rax, rbx
    mov [rsp+24], rax
    lea rax, [rsp+8]
    mov [rbp-112], rax
    lea rax, [str_11]
    mov rdi, rax
    call print_str
    mov rax, [rbp-112]
    push rax
    mov rax, 1
    mov rcx, rax
    pop rax
    mov rax, [rax+rcx*8]
    mov rdi, rax
    call print_int
    lea rax, [str_2]
    mov rdi, rax
    call print_str
    xor rax, rax
    add rsp, 256
    pop r15
    pop r14
    pop r13
    pop r12
    pop rbx
    mov rsp, rbp
    pop rbp
    ret

_start:
    call _main
    mov rdi, rax
    mov rax, 60
    syscall
