; Generated by ELang compiler v0.2.0
extern print
extern print_str
extern print_int
extern print_hex
extern read_input
extern exit
extern str_len
extern str_dup
extern str_cmp
extern str_cat
extern sys_open
extern sys_close
extern sys_read
extern sys_write
extern sys_getpid
extern sys_exit
extern sys_brk
extern panic_handler
extern assert_handler
section .data
  str_0: db 'H', 'e', 'l', 'l', 'o', ',', ' ', 'E', 'L', 'a', 'n', 'g', '!', 0x0A, 0
  str_1: db 'S', 'u', 'm', ':', ' ', 0
  str_2: db 0x0A, 0
  str_3: db 'x', ' ', 'i', 's', ' ', 'p', 'o', 's', 'i', 't', 'i', 'v', 'e', 0x0A, 0
  str_4: db 'L', 'o', 'o', 'p', ':', ' ', 0
  str_5: db 0x0A, 0
  str_6: db 'F', 'o', 'r', ':', ' ', 0
  str_7: db 0x0A, 0
  str_8: db 'D', 'i', 'v', 'i', 'd', 'e', ':', ' ', 0
  str_9: db 0x0A, 0
  str_10: db 'D', 'i', 'v', 'i', 'd', 'e', ' ', 'b', 'y', ' ', 'z', 'e', 'r', 'o', ':', ' ', 0
  str_11: db 0x0A, 0
section .text
global _start


global _main
_main:
    push rbp
    mov rbp, rsp
    push rbx
    push r12
    push r13
    push r14
    push r15
    sub rsp, 256
    lea rax, [str_0]
    mov rdi, rax
    call print_str
    mov rax, 42
    mov [rbp-48], rax
    mov rax, 100
    mov [rbp-56], rax
    mov rax, [rbp-48]
    push rax
    mov rax, [rbp-56]
    mov rbx, rax
    pop rax
    add rax, rbx
    mov [rbp-64], rax
    lea rax, [str_1]
    mov rdi, rax
    call print_str
    mov rax, [rbp-64]
    mov rdi, rax
    call print_int
    lea rax, [str_2]
    mov rdi, rax
    call print_str
    mov rax, [rbp-48]
    push rax
    mov rax, 0
    mov rbx, rax
    pop rax
    cmp rax, rbx
    setg al
    movzx rax, al
    cmp rax, 0
    je L12
    lea rax, [str_3]
    mov rdi, rax
    call print_str
L12:
    mov rax, 0
    mov [rbp-72], rax
L14:
    mov rax, [rbp-72]
    push rax
    mov rax, 5
    mov rbx, rax
    pop rax
    cmp rax, rbx
    setl al
    movzx rax, al
    cmp rax, 0
    je L15
    lea rax, [str_4]
    mov rdi, rax
    call print_str
    mov rax, [rbp-72]
    mov rdi, rax
    call print_int
    lea rax, [str_2]
    mov rdi, rax
    call print_str
    mov rax, [rbp-72]
    push rax
    mov rax, 1
    mov rbx, rax
    pop rax
    add rax, rbx
    mov [rbp-72], rax
    jmp L14
L15:
    mov rax, 0
    push rax
    mov rax, 3
    push rax
    pop rax
    mov [rbp-80], rax
    pop rax
    mov [rbp-88], rax
L16:
    mov rax, [rbp-88]
    mov rbx, [rbp-80]
    cmp rax, rbx
    jge L17
    lea rax, [str_6]
    mov rdi, rax
    call print_str
    mov rax, [rbp-88]
    mov rdi, rax
    call print_int
    lea rax, [str_2]
    mov rdi, rax
    call print_str
L18:
    mov rax, [rbp-88]
    inc rax
    mov [rbp-88], rax
    jmp L16
L17:
    mov rax, 2
    mov rsi, rax
    mov rax, 10
    mov rdi, rax
    call _divide
    push rax
    mov rax, [rsp]
    mov rbx, rax
    and rbx, 1
    cmp rbx, 0
    jne L21
    shr rax, 1
    mov [rbp-104], rax
    mov rax, [rbp-104]
    push rax
    jmp L19
L21:
    mov rax, [rsp]
    mov rbx, rax
    and rbx, 1
    cmp rbx, 1
    jne L22
    shr rax, 1
    mov [rbp-112], rax
    mov rax, 0
    push rax
    jmp L19
L22:
    add rsp, 8
L19:
    pop rax
L20:
    mov [rbp-96], rax
    lea rax, [str_8]
    mov rdi, rax
    call print_str
    mov rax, [rbp-96]
    mov rdi, rax
    call print_int
    lea rax, [str_2]
    mov rdi, rax
    call print_str
    mov rax, 0
    mov rsi, rax
    mov rax, 10
    mov rdi, rax
    call _divide
    push rax
    mov rax, [rsp]
    mov rbx, rax
    and rbx, 1
    cmp rbx, 0
    jne L25
    shr rax, 1
    mov [rbp-112], rax
    mov rax, [rbp-112]
    push rax
    jmp L23
L25:
    mov rax, [rsp]
    mov rbx, rax
    and rbx, 1
    cmp rbx, 1
    jne L26
    shr rax, 1
    mov [rbp-120], rax
    mov rax, 0
    push rax
    jmp L23
L26:
    add rsp, 8
L23:
    pop rax
L24:
    mov [rbp-104], rax
    lea rax, [str_10]
    mov rdi, rax
    call print_str
    mov rax, [rbp-104]
    mov rdi, rax
    call print_int
    lea rax, [str_2]
    mov rdi, rax
    call print_str
    xor rax, rax
    add rsp, 256
    pop r15
    pop r14
    pop r13
    pop r12
    pop rbx
    mov rsp, rbp
    pop rbp
    ret

global _add
_add:
    push rbp
    mov rbp, rsp
    push rbx
    push r12
    push r13
    push r14
    push r15
    mov [rbp-48], rdi
    mov [rbp-56], rsi
    sub rsp, 256
    mov rax, [rbp-48]
    push rax
    mov rax, [rbp-56]
    mov rbx, rax
    pop rax
    add rax, rbx
    mov rsp, rbp
    pop rbp
    ret
    add rsp, 256
    pop r15
    pop r14
    pop r13
    pop r12
    pop rbx
    mov rsp, rbp
    pop rbp
    ret

global _divide
_divide:
    push rbp
    mov rbp, rsp
    push rbx
    push r12
    push r13
    push r14
    push r15
    mov [rbp-48], rdi
    mov [rbp-56], rsi
    sub rsp, 256
    mov rax, [rbp-56]
    push rax
    mov rax, 0
    mov rbx, rax
    pop rax
    cmp rax, rbx
    sete al
    movzx rax, al
    cmp rax, 0
    je L27
    mov rax, 0
    shl rax, 1
    or rax, 1
    mov rsp, rbp
    pop rbp
    ret
L27:
    mov rax, [rbp-48]
    push rax
    mov rax, [rbp-56]
    mov rbx, rax
    pop rax
    cqo
    idiv rbx
    shl rax, 1
    mov rsp, rbp
    pop rbp
    ret
    add rsp, 256
    pop r15
    pop r14
    pop r13
    pop r12
    pop rbx
    mov rsp, rbp
    pop rbp
    ret

_start:
    call _main
    mov rdi, rax
    mov rax, 60
    syscall
