/* ELang Token definitions */
#ifndef ELANG_TOKEN_H
#define ELANG_TOKEN_H

#include <stddef.h>

typedef enum {
    TOKEN_INT_LIT, TOKEN_FLOAT_LIT, TOKEN_STRING_LIT, TOKEN_CHAR_LIT,
    TOKEN_BOOL_LIT, TOKEN_IDENT,
    TOKEN_FN, TOKEN_RETURN, TOKEN_IF, TOKEN_ELSE, TOKEN_WHILE, TOKEN_FOR,
    TOKEN_IN, TOKEN_LOOP, TOKEN_BREAK, TOKEN_CONTINUE, TOKEN_MATCH, TOKEN_WHEN,
    TOKEN_LET, TOKEN_MUT, TOKEN_CONST, TOKEN_STRUCT, TOKEN_ENUM,
    TOKEN_IMPORT, TOKEN_EXPORT, TOKEN_AS, TOKEN_USING, TOKEN_DEFER,
    TOKEN_TRUE, TOKEN_FALSE, TOKEN_NIL,
    TOKEN_TYPE, TOKEN_VOID, TOKEN_I8, TOKEN_I16, TOKEN_I32, TOKEN_I64,
    TOKEN_U8, TOKEN_U16, TOKEN_U32, TOKEN_U64, TOKEN_F32, TOKEN_F64,
    TOKEN_BOOL, TOKEN_CHAR, TOKEN_STRING,
    TOKEN_ERROR_TYPE, TOKEN_OK, TOKEN_ERR, TOKEN_RESULT,
    TOKEN_ALLOC, TOKEN_FREE, TOKEN_SYSCALL, TOKEN_PANIC, TOKEN_ASSERT,
    TOKEN_CATCH, TOKEN_QUESTION,
    TOKEN_PLUS, TOKEN_MINUS, TOKEN_STAR, TOKEN_SLASH, TOKEN_PERCENT,
    TOKEN_EQ, TOKEN_NEQ, TOKEN_LT, TOKEN_GT, TOKEN_LTE, TOKEN_GTE,
    TOKEN_AND, TOKEN_OR, TOKEN_NOT,
    TOKEN_ASSIGN, TOKEN_PLUS_ASSIGN, TOKEN_MINUS_ASSIGN,
    TOKEN_STAR_ASSIGN, TOKEN_SLASH_ASSIGN, TOKEN_PERCENT_ASSIGN,
    TOKEN_AMP, TOKEN_PIPE, TOKEN_CARET, TOKEN_TILDE,
    TOKEN_LSHIFT, TOKEN_RSHIFT, TOKEN_ARROW, TOKEN_FAT_ARROW, TOKEN_PIPE_ARROW,
    TOKEN_DOT, TOKEN_DOTDOT, TOKEN_COLON, TOKEN_COLONCOLON, TOKEN_SEMICOLON, TOKEN_COMMA,
    TOKEN_LPAREN, TOKEN_RPAREN, TOKEN_LBRACE, TOKEN_RBRACE,
    TOKEN_LBRACKET, TOKEN_RBRACKET,
    TOKEN_NEWLINE, TOKEN_EOF, TOKEN_ERROR,
} token_type_t;

typedef struct {
    token_type_t type;
    const char *value;
    size_t length;
    int line;
    int col;
} token_t;

token_t token_create(token_type_t type, const char *value, size_t length, int line, int col);
const char *token_type_name(token_type_t type);

#endif
